spring:
  application:
    name: mycoolapp
  team:
    name: Satheesh
    security:
      enabled: true
      username: satheesh
      password: satheesh

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: My Cool App
    description: This is a cool application built with Spring Boot.
    version: 1.0.0
